### PR TITLE
Fix/49 cannot find context with specified id

### LINKED ISSUE #49: Cannot find context with specified id
Reported by Tom on Oct, 30th:

* I was getting nil pointer exceptions here and somewhere here as a result of frame being nil. Moving the if blocks inside the preceding if `frame != nil` block got me past these. Not sure what the implications are beyond that though, but I guess having a nil frame is expected if there's already code checking for that condition?! :sweat_smile:
* Currently seeing a `ERRO[0026] unable to evaluate expression: Cannot find context with specified id (-32000)`. Not sure why - I think this was working before I pulled the latest `xk6-browser`.
* Also seeing a `panic: send on closed channel` but I think that might be happening as a result of earlier errors (like the above), i.e. during shutdown.

<details>
<summary>Example stack trace</summary>

```
panic: send on closed channel

goroutine 46 [running]:
go.k6.io/k6/stats.PushIfNotDone(...)
        go.k6.io/k6@v0.34.1/stats/stats.go:433
github.com/grafana/xk6-browser/common.(*NetworkManager).emitResponseReceived(0xc0010c0280, 0xc0006085b0)
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:131 +0x87a
github.com/grafana/xk6-browser/common.(*NetworkManager).onResponseReceived(0xc0010c0280, 0xc0005de8c0)
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:356 +0xc5
github.com/grafana/xk6-browser/common.(*NetworkManager).handleEvents(0xc0010c0280, 0xc00057a5a0)
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:245 +0x1cf
github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents.func1()
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:220 +0x37
created by github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:219 +0x125
```

</details>

Here's the JS code I'm running, with the failure happening in `clickBrowseDesigns` (which is odd as it is very similar to the preceding `clickBusinessCards`).

<details>

<summary>Script</summary>

```javascript
import { sleep, group } from 'k6';
import launcher from 'k6/x/browser';

import { randomIntBetween } from 'https://jslib.k6.io/k6-utils/1.1.0/index.js';

export const options = {};

let browser, context, page;

const pauseMin = 1;
const pauseMax = 1;

export default function() {
  initialize();
  
  navigateToHomepage();
  clickBusinessCards();
  clickBrowseDesigns();
  clickDesign('Standard (3.5" x 2")');
}

function initialize() {
  browser = launcher.launch('chromium', {
    args: [],
    debug: false,
    devtools: false,
    env: {},
    executablePath: null,
    headless: false,
    ignoreDefaultArgs: [],
    proxy: {},
    slowMo: '500ms',
    timeout: '30s',
  });

  context = browser.newContext({
    ignoreHTTPSErrors: true
  });

  page = context.newPage();
}

function navigateToHomepage() {
  group("Navigate to Homepage", () => {
    page.goto('https://vistaprint.ca', { waitUntil: 'domcontentloaded' });
  });

  sleep(randomIntBetween(pauseMin, pauseMax));
}

function clickBusinessCards() {
  const elem = page.$("//span[text()='Business Cards']");

  console.log(JSON.stringify(elem));

  group("Click Business Cards", () => {
    elem.click();
    
    // Wait for next page to load
    page.waitForLoadState('networkidle');
  });

  sleep(randomIntBetween(pauseMin, pauseMax));
}

function clickBrowseDesigns() {
  const elem = page.$("//a[text()='Browse designs']");

  console.log(JSON.stringify(elem));

  group("Click Browse Designs", () => {
    elem.click();
    
    page.waitForLoadState('networkidle');
  });

  sleep(randomIntBetween(pauseMin, pauseMax));
}

function clickDesign(designName) {
  // fetch all of the design options
  const designOptions = page.$("li.design-tile");
  console.log(JSON.stringify(designOptions));
  console.log(`Found ${designOptions.length} design options.`);

  console.log(`Selecting "${designName}"...`);

  JSON.stringify(designOptions);
}
```

</details>

---

[This PR](https://github.com/grafana/xk6-browser/pull/50) fixes the `nil pointer` issues.

### PR DESCRIPTION
**Pull request by inancgumus**
This PR fixes #49 for good 🎉

After long debugging sessions and trials, finally, I figured out the problem: `FrameSession` was blocking frame handling, and the rest of the system couldn't propagate execution contexts, causing the `context with specified id not found` error. This misbehavior happens because a `Session` can get closed while a `FrameSession` is in the initialization stage.

The only error we are receiving is different now: `wait for selector didn't result in any nodes` on the `Click Continue (Recommendations)` group. I tested this patch with Chromium 98.0.4753.0. I also tested this with other test runners, and they stuck on the same step. I'm going to create a new issue for it.

<details>
<summary>Here's the script I'm using. It's a more concise and faster (_pauseMin/Max_) version of Tom's original script.</summary>

```javascript
import { sleep, group } from 'k6';
import launcher from 'k6/x/browser';

import { randomIntBetween } from 'https://jslib.k6.io/k6-utils/1.1.0/index.js';

export const options = {};

export default function () {
        const pauseMin = 1;
        const pauseMax = 2;

        let browser = launcher.launch('chromium', {
                args: [],
                debug: false,
                devtools: false,
                env: {},
                executablePath: null,
                headless: false,
                ignoreDefaultArgs: [],
                proxy: {},
                slowMo: '500ms',
                timeout: '30s',
        });

        let context = browser.newContext({
                ignoreHTTPSErrors: true,
                screen: { width: 1920, height: 1080 },
                viewport: { width: 1920, height: 1080 },
        });

        let page = context.newPage();

        group("Navigate to Homepage", () => {
                console.log('Starting navigateToHomepage...');
                // page.goto('https://vistaprint.ca', { waitUntil: 'networkidle' });
                page.goto('https://vistaprint.ca');
                sleep(randomIntBetween(pauseMin, pauseMax));
        });

        group("Click Business Cards", () => {
                console.log('Starting clickBusinessCards...');
                page.waitForSelector("//span[text()='Business Cards']").click();
                sleep(randomIntBetween(pauseMin, pauseMax));
        });

        group("Click Browse Designs", () => {
                console.log('Starting clickBrowseDesigns...');
                page.waitForSelector("//a[text()='Browse designs']").click();
                sleep(randomIntBetween(pauseMin, pauseMax));
        });

        group("Select Design Option", () => {
                console.log('Starting clickDesign...');

                // const designOptions = page.$$("li.design-tile");
                // console.log(`Found ${designOptions.length} design options.`);

                const designOption = page.waitForSelector(`li.design-tile:first-child`);
                console.log("Design options:", designOption.textContent());
                designOption.click();
                sleep(randomIntBetween(pauseMin, pauseMax));
        });

        group("Click Customize Design", () => {
                console.log('Starting clickCustomizeDesign...');
                page.waitForSelector("//a[text()='Customize this design']").click();
                sleep(randomIntBetween(pauseMin, pauseMax));
        });


        group("Click Next", () => {
                console.log('Starting clickNext...');
                page.waitForSelector("//button[text()='Next']").click();
                sleep(randomIntBetween(pauseMin, pauseMax));
        });

        group("Click Continue Without Back", () => {
                console.log('Starting continueWithoutBack...');
                page.waitForSelector("//button[text()='Continue without back']").click();
                sleep(randomIntBetween(pauseMin, pauseMax));
        });

        group("Click Customer Reviewed", () => {
                console.log('Starting customerReviewed...');

                page.waitForSelector("//input[@value='customerReviewed']").click();
                sleep(1);

                page.waitForSelector("//button[text()='Continue']").click();
                sleep(randomIntBetween(pauseMin, pauseMax));
        });

        group("Click Add to Cart", () => {
                console.log('Starting addToCart...');
                page.waitForSelector("//button[text()='Add to cart']").click();
                sleep(randomIntBetween(pauseMin, pauseMax));
        });

        group("Click Continue (Recommendations)", () => {
                console.log('Starting continuePastRecommendations...');
                page.waitForSelector("//button[text()='Add to cart']").click(); // works
                
                // const els = page.$$("//a[text()='Continue']");
                // els[0].click();
                page.waitForSelector("//a[text()='Continue']").click();
                sleep(randomIntBetween(pauseMin, pauseMax));
        });

        group("Click Continue to Cart", () => {
                console.log('Starting continueToCart...');

                page.waitForSelector(".slim-footer"); // works
                // const els = page.$$("//a[text()='Continue to cart']");
                // els[0].click();
                page.waitForSelector("//a[text()='Continue to cart']").click();

                sleep(randomIntBetween(pauseMin, pauseMax));
        });

        group("Click Checkout", () => {
                console.log('Starting goToCheckout...');
                page.waitForSelector("//a[text()='Checkout']").click();
                sleep(randomIntBetween(pauseMin, pauseMax));
        });
}
```

</details>

<details>
<summary>Here's Tom's original script that also runs without context errors. I just added a `waitForNavigation` call before `page.waitForSelector("//span[text()='Step 4']");`.</summary>

```javascript
import { sleep, group } from 'k6';
import launcher from 'k6/x/browser';

import { randomIntBetween } from 'https://jslib.k6.io/k6-utils/1.1.0/index.js';

export const options = {};

let browser, context, page;

const pauseMin = 10;
const pauseMax = 10;

export default function () {
        initialize();

        navigateToHomepage();
        clickBusinessCards();
        clickBrowseDesigns();
        clickDesign();
        clickCustomizeDesign();
        clickNext();
        continueWithoutBack();
        customerReviewed();
        addToCart();
        continuePastRecommendations();
        continueToCart();
        goToCheckout();
}

function initialize() {
        browser = launcher.launch('chromium', {
                args: [],
                debug: false,
                devtools: false,
                env: {},
                executablePath: null,
                headless: false,
                ignoreDefaultArgs: [],
                proxy: {},
                slowMo: '500ms',
                timeout: '30s',
        });

        context = browser.newContext({
                ignoreHTTPSErrors: true,
                screen: { width: 1920, height: 1080 },
                viewport: { width: 1920, height: 1080 },
        });

        page = context.newPage();
}

function navigateToHomepage() {
        console.log('Starting navigateToHomepage...');

        group("Navigate to Homepage", () => {
                page.goto('https://vistaprint.ca', { waitUntil: 'networkidle' });

                // Wait for a specific element to appear
                page.waitForSelector(".fluid-image");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}

function clickBusinessCards() {
        console.log('Starting clickBusinessCards...');

        const elem = page.$("//span[text()='Business Cards']");

        group("Click Business Cards", () => {
                elem.click();

                page.waitForSelector("//a[text()='Browse designs']");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}

function clickBrowseDesigns() {
        console.log('Starting clickBrowseDesigns...');

        const elem = page.$("//a[text()='Browse designs']");

        group("Click Browse Designs", () => {
                elem.click();

                page.waitForSelector("li.design-tile");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}

function clickDesign() {
        console.log('Starting clickDesign...');

        // fetch all of the design options
        const designOptions = page.$$("li.design-tile");
        console.log(`Found ${designOptions.length} design options.`);

        /*
        designOptions.some((designOption) => {
          const designOptionName = designOption.textContent();
          console.log(`Design option: ${designOptionName}`);
      
          if (designOptionName === designName) {
            console.log(`Selecting "${designName}"...`);
      
            group("Select Design Option", () => {
              designOption.click();
      
              page.waitForSelector("//a[text()='Customize this design']");
            });
      
            return true;
          }
        });
        */ // no bueno

        /*
        page.$$("li.design-tile", (designOption) => {
          const designOptionName = designOption.textContent();
          console.log(`Design option: ${designOptionName}`);
      
          if (designOptionName === designName) {
            console.log(`Selecting "${designName}"...`);
      
            group("Select Design Option", () => {
              designOption.click();
      
              page.waitForSelector("//a[text()='Customize this design']");
            });
      
            return true;
          }
        });
        */ // also no bueno

        const designOption = page.$(`li.design-tile >> nth=0`);
        console.log(designOption.textContent());

        group("Select Design Option", () => {
                designOption.click();

                page.waitForSelector("//a[text()='Customize this design']");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}

function clickCustomizeDesign() {
        console.log('Starting clickCustomizeDesign...');

        const elem = page.$("//a[text()='Customize this design']");

        group("Click Customize Design", () => {
                elem.click();

                page.waitForSelector("//button[text()='Next']");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}

function clickNext() {
        console.log('Starting clickNext...');

        const elem = page.$("//button[text()='Next']");

        group("Click Next", () => {
                elem.click();

                page.waitForSelector("//button[text()='Continue without back']");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}

function continueWithoutBack() {
        console.log('Starting continueWithoutBack...');

        const elem = page.$("//button[text()='Continue without back']");

        group("Click Continue Without Back", () => {
                elem.click();

                page.waitForSelector("//input[@value='customerReviewed']");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}

function customerReviewed() {
        console.log('Starting customerReviewed...');

        let elem = page.$("//input[@value='customerReviewed']");
        elem.click();

        sleep(5);

        elem = page.$("//button[text()='Continue']");

        group("Click Customer Reviewed", () => {
                elem.click();

                page.waitForNavigation();
                page.waitForSelector("//span[text()='Step 4']");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}

function addToCart() {
        console.log('Starting addToCart...');

        const elem = page.$("//button[text()='Add to cart']");

        group("Click Add to Cart", () => {
                elem.click();

                page.waitForSelector("//a[text()='Continue']");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}

function continuePastRecommendations() {
        console.log('Starting continuePastRecommendations...');

        const elem = page.$("//a[text()='Continue']");

        group("Click Continue (Recommendations)", () => {
                elem.click();

                page.waitForSelector("//a[text()='Continue to cart']");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}

function continueToCart() {
        console.log('Starting continueToCart...');

        const elem = page.$("//a[text()='Continue to cart']");

        group("Click Continue to Cart", () => {
                elem.click();

                page.waitForSelector("//a[text()='Checkout']");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}

function goToCheckout() {
        console.log('Starting goToCheckout...');

        const elem = page.$("//a[text()='Checkout']");

        group("Click Checkout", () => {
                elem.click();

                page.waitForSelector("//button[text()='Sign in']");
        });

        sleep(randomIntBetween(pauseMin, pauseMax));
}
```

</details>

<details>
<summary>Here's another script Tom has shared on Jan 4th, 2022. I modified it a little bit to wait for navigation.</summary>

```javascript
import launcher from 'k6/x/browser';
import { check, group, sleep } from 'k6';

export default function () {
  const browser = launcher.launch('chromium', {
    headless: false,
    // slowMo: '500ms' // slow down by 500ms
  });
  
  let context = browser.newContext({    
    // hack:
    // Without setting viewport, the script cannot find the add-to-cart
    // element. We might want to improve this.

    // screen: { width: 1920, height: 1080 },
    // viewport: { width: 1920, height: 1080 },
  });

  const page = context.newPage();

  group("Navigate to Homepage", () => {
    page.goto('http://ecommerce.test.k6.io/', { waitUntil: 'networkidle' });
  });

  sleep(2);

  group("Click Product", () => {
    page.waitForSelector('.woocommerce-result-count');
    page.click('.woocommerce-loop-product__title');
  });
  
  sleep(2);

  group("Click Add to Cart", () => {
    console.log("Clicking Add to Cart...");

    // wait for the element to be attached
    let b = page.waitForSelector('button[name="add-to-cart"]');

    // hack: scroll the element into view
    page.evaluate(() => {
      const el = document.querySelector('button[name="add-to-cart"]');
      el.scrollIntoView();
    });
    b.click();

    // 💣 💣 💣
    // we wait for navigation to happen
    // before waiting for a selector.
    page.waitForNavigation();
	
    // page is properly navigated. let's
    // wait for the selector.
    console.log("Waiting for .woocommerce-message...");
    page.waitForSelector('.woocommerce-message'); 
  });

  sleep(2);

  group("View Cart", () => {
    page.click('.cart-contents');
    page.waitForSelector('.woocommerce-cart-form__cart-item');
  });
  
  sleep(2);

  page.close();
  browser.close();
}
```

</details>

### CODE REVIEW

File: common/frame_session.go [hunk 1]
```diff
@@ -776,94 +781,109 @@ func (fs *FrameSession) onPageNavigatedWithinDocument(event *cdppage.EventNaviga
...
-			return
-		default:
-			k6Throw(fs.ctx, "cannot create frame session (iframe): %w", err)
-		}
-	}
-
-	if event.TargetInfo.Type != "worker" {
-		fs.logger.Debugf("FrameSession:onAttachedToTarget returns: target is not a worker",
-			"sid:%v tid:%v esid:%v etid:%v ebctxid:%v type:%q",
+	if session == nil {
```
Comment (robingustafsson) [inline common/frame_session.go:793]: Is this the fail-fast fix you mention? It's interesting that a session isn't available at this point considering that we always handle session creation/destruction before forwarding a CDP message to the higher layers (see https://github.com/grafana/xk6-browser/blob/8c7fc3b5e38e41488c833f38853190cd679c2589/common/connection.go#L280-L304).

**Review by robingustafsson — COMMENTED** [review]
Disclaimer: I haven't run the code, just looked at it 🙂

You mention in one of the commit comments:
> It also changes the ordering of FrameSession
init steps. The reason of putting initOptions
last is: It was propagating frame events
before the frame is ready to be used.

Could you share more info here, what was being propagated by `initOptions`? From what I know it's the enabling of domains and the `target.SetAutoAttach` call in `initDomains` that triggers the browser to report all frames and execution contexts etc.

**Comment by inancgumus** [comment]
> Could you share more info here, what was being propagated by initOptions? From what I know it's the enabling of domains and the target.SetAutoAttach call in initDomains that triggers the browser to report all frames and execution contexts etc.

@robingustafsson, yes, you're right: It triggers a lot of things. That's why I put it last for safety. I wanted a `FrameSession` to get initialized first without dealing with a lot of CDP messages. But it doesn't change anything in general. I can revert it back if you want.

What this fix is all about is to terminate `FrameSession` initialization in a fail-fast fashion when its `Session` is told to be closed by the browser:

https://github.com/grafana/xk6-browser/pull/169/files#diff-7a16e0aa3a4b58ec5d9a27fc5e2907c7ca981226a4f4dbd60105964855eac5f7R67-R77

https://github.com/grafana/xk6-browser/pull/169/files#diff-0322ba3112bd52435894949eeb4b5e8cc203dd70e182cc1f89fae50e770c880cR181

https://github.com/grafana/xk6-browser/pull/169/files#diff-2a8b700bc15b2ce068271ee5df1e3f848a5d2e8dcfdf3cc1958dc0694249db08R245-R248

https://github.com/grafana/xk6-browser/pull/169/files#diff-2a8b700bc15b2ce068271ee5df1e3f848a5d2e8dcfdf3cc1958dc0694249db08R840-R842

https://github.com/grafana/xk6-browser/pull/169/files#diff-0322ba3112bd52435894949eeb4b5e8cc203dd70e182cc1f89fae50e770c880cR226

File: common/frame_session.go (hunk 1 above)
Comment (inancgumus) [reply common/frame_session.go:793]: No, this is not the fail-fast fix :) I explained it in my other comment [here](https://github.com/grafana/xk6-browser/pull/169#issuecomment-1004843769).

This check is needed because sometimes there is a small window where a session can get removed by the connection while a new `FrameSession` is being constructed.

The `Session` is closed and removed by the `Connection`:

```
TRAC[0018] <- {"method":"Target.detachedFromTarget","params":{"sessionId":"CB2EC5F869C50B25582486DA64B58901","targetId":"CE598CB4776BC46D2EDFD02BE605CB4B"},"sessionId":"34759DABAC917ACD14805A6CCD588A99"}  category="cdp:recv" elapsed="0 ms" goroutine=40
DEBU[0018] sid:CB2EC5F869C50B25582486DA64B58901 tid:CE598CB4776BC46D2EDFD02BE605CB4B wsURL:ws://127.0.0.1:55791/devtools/browser/e5adcaf1-d538-4f52-bb1e-fa1f0f04eac9  category="Connection:closeSession" elapsed="0 ms" goroutine=40
DEBU[0018] sid:CB2EC5F869C50B25582486DA64B58901 tid:CE598CB4776BC46D2EDFD02BE605CB4B  category="Session:close" elapsed="0 ms" goroutine=40
DEBU[0018] sid:CB2EC5F869C50B25582486DA64B58901 tid:CE598CB4776BC46D2EDFD02BE605CB4B  category="Session:readLoop:<-s.done" elapsed="0 ms" goroutine=8742
```

Right after, a new `FrameSession` is getting created (`Session` becomes `nil` here):

```
DEBU[0018] sid:34759DABAC917ACD14805A6CCD588A99 tid:3A13FFBEA431F41D61631412B66A4563 esid:CB2EC5F869C50B25582486DA64B58901 etid:CE598CB4776BC46D2EDFD02BE605CB4B ebctxid:3A834A21E6848FC15E6107ADAF48043B type:"iframe"  category="FrameSession:onAttachedToTarget" elapsed="0 ms" goroutine=104
```

This happens 10% of the time among all the new `FrameSession` initializations.

File: common/session.go [hunk 2]
```diff
@@ -194,9 +192,8 @@ func (s *Session) ExecuteWithoutExpectationOnReply(ctx context.Context, method s
 		return ErrTargetCrashed
 	}
 
-	id := atomic.AddInt64(&s.msgID, 1)
+	s.logger.Debugf("Session:Execute:s.conn.send", "sid:%v tid:%v method:%q", s.id, s.targetID, method)
```
[the remark this answers is not in the document]
Comment (inancgumus) [reply common/session.go:195]: I don't log `msgID` there? I guess the change on Github shows like so 🤷 😄  Here's the full method:

https://github.com/grafana/xk6-browser/blob/bce2f5434fb89d1f790c1ba29529344461946a7f/common/session.go#L184-L227

[the remark this answers is not in the document]
Comment (robingustafsson) [reply common/session.go:195]: Haha, my bad, I misread 😅

File: common/frame_session.go (hunk 1 above)
Comment (robingustafsson) [reply common/frame_session.go:793]: Ah I see, thanks for clarifying.

**Comment by robingustafsson** [comment]
Ah wait, I see now in the code that you actually put `initDomains()` last and NOT `initOptions()` as your commit comment says. I think I got confused and reacted to the commit comment rather than looking at the code 😅 All good then.

Thanks for clarifying the fail-fast fix as well, I see now that it's the "auto-cancellation" of the context when `done`channel is closed that makes the execution short-circuit and fail-fast.

**Comment by inancgumus** [comment]
Yeah, my bad, sorry 🤦

Yes, exactly, that's what I mean by failing-fast 😄

**Comment by inancgumus** [comment]
> All good then.

@robingustafsson Does that mean you approve the PR? :) Can I include this fix in Friday's release?

**Comment by robingustafsson** [comment]
Yes, it's good to go (I can't seem to change my review to approve) 🙂
