### PR TITLE
Fix: panic on navigating on remote iframes

### LINKED ISSUE #669: Panic while navigating to some websites
### Brief summary

Tom found an interesting edge case where when navigating to a select website caused it to panic. We're not sure why that currently occurs but what we get is the following error:

```shell
panic: GoError: handling frameNavigated event to "about:blank": we either navigate top level or have old version of the navigated frame
```

### xk6-browser version

v0.6.0

### OS

MacOS 12.6

### Chrome version

Version 108.0.5359.71 (Official Build) (arm64)

### Docker version and image (if applicable)

NA

### Steps to reproduce the problem

Use the `panic-site-goto.js` script from the complex scripts folder and run it against `v0.6.0` of xk6-browser.

### Expected behaviour

It should successfully navigate to the site under test without panicking.

### Actual behaviour

It panics.

### PR DESCRIPTION
**Pull request by ankur22**
Fixes: https://github.com/grafana/xk6-browser/issues/669

# Prerequisite

This requires some background reading on how `iframe`s are rendered: https://developer.chrome.com/articles/renderingng-architecture/ -- specifically around the [blink renderer](https://developer.chrome.com/articles/renderingng-architecture/#render-process-main-thread-components) which renders frames on different processes depending on if the `iframe` is from the same/current origin (e.g. k6.io) vs from a different origin (e.g. youtube.com).

Puppeteer: https://github.com/puppeteer/puppeteer/commit/4d9dc8c0e613f22d4cdf237e8bd0b0da3c588edb
Playwright: https://github.com/microsoft/playwright/commit/38fadcaded8c337d514c10db6f1c207f11e2f532

# Investigation

Here's the example website used to debug the issue:

```html
<html>
    <head></head>
    <body>
        <iframe src="https://www.youtube.com/embed/gwO7k5RTE54?wmode=opaque&amp;enablejsapi=1"></iframe>
    </body>
</html>
```

Why is `xk6-browser` panicking when it navigates to certain websites? Using the logs and the specified website, it showed that the new frame with an embedded youtube video couldn't be attached to its parent frame since `xk6-browser` was deleting the parent frame from the tree:

```
// xk6-browser first navigates to about:blank.
onFrameNavigated sid:6D13FFCBEEEBDF7A2D25A3D752665F3E tid:9A6048556C8F260031B29E6904CEDD74 fid:9A6048556C8F260031B29E6904CEDD74
FrameManager:frameNavigated fid:9A6048556C8F260031B29E6904CEDD74 pfid: docid:23336728A436D9DE441088A2FF2E8801 fname: furl:about:blank initial:true
// Now it navigates to a test page with an embedded video.
onFrameNavigated sid:6D13FFCBEEEBDF7A2D25A3D752665F3E tid:9A6048556C8F260031B29E6904CEDD74 fid:9A6048556C8F260031B29E6904CEDD74
FrameManager:frameNavigated fid:9A6048556C8F260031B29E6904CEDD74 pfid: docid:2105D98CAFCAFCBF61926EC686DDBBC8 fname: furl:http://localhost:8080/embed-youtube initial:false
// Chrome sends a signal that a child frame is being attached.
onFrameAttached sid:6D13FFCBEEEBDF7A2D25A3D752665F3E tid:9A6048556C8F260031B29E6904CEDD74 fid:4E07510D2F5ED2D15367F9C84839737D pfid:9A6048556C8F260031B29E6904CEDD74
FrameManager:frameAttached no frame exists fmid:1 fid:4E07510D2F5ED2D15367F9C84839737D pfid:9A6048556C8F260031B29E6904CEDD74
FrameManager:frameAttached new frame fmid:1 fid:4E07510D2F5ED2D15367F9C84839737D pfid:9A6048556C8F260031B29E6904CEDD74
// Navigate to about:blank initially in the iframe (newly attache child frame).
onFrameNavigated sid:BE8A4A02AE79ED9590C3656367DEA2B8 tid:4E07510D2F5ED2D15367F9C84839737D fid:4E07510D2F5ED2D15367F9C84839737D
FrameManager:frameNavigated fid:4E07510D2F5ED2D15367F9C84839737D pfid:9A6048556C8F260031B29E6904CEDD74 docid:EAF6A40F4EB139978F4BE3A693A9E6E2 fname: furl:https://www.youtube.com/embed/gwO7k5RTE54?wmode=opaque&enablejsapi=1 initial:false
// Frame is detached to show that a different process will take over the rendering of the child frame since it's a remote frame (not from the current site origin). xk6-browser will delete the frame from the tree.
FrameManager:frameDetached fmid:1 fid:4E07510D2F5ED2D15367F9C84839737D reason:swap
// Remote frame is being attached.
onFrameAttached sid:BE8A4A02AE79ED9590C3656367DEA2B8 tid:4E07510D2F5ED2D15367F9C84839737D fid:36406088C5AB20583D2DA08AF31E4370 pfid:4E07510D2F5ED2D15367F9C84839737D
FrameManager:frameAttached no frame exists fmid:1 fid:36406088C5AB20583D2DA08AF31E4370 pfid:4E07510D2F5ED2D15367F9C84839737D
// This is the problem here -- the parent frame with fid 4E07510D2F5ED2D15367F9C84839737D was deleted above.
FrameManager:frameAttached no parent frame exists fmid:1 fid:36406088C5AB20583D2DA08AF31E4370 pfid:4E07510D2F5ED2D15367F9C84839737D
onFrameNavigated sid:BE8A4A02AE79ED9590C3656367DEA2B8 tid:4E07510D2F5ED2D15367F9C84839737D fid:36406088C5AB20583D2DA08AF31E4370
FrameManager:frameNavigated fid:36406088C5AB20583D2DA08AF31E4370 pfid:4E07510D2F5ED2D15367F9C84839737D docid:A2C16738A5F0D984DC6D41A83BE8BE24 fname: furl:about:blank initial:false
panic: GoError: handling frameNavigated event to "about:blank": we either navigate top level or have old version of the navigated frame
```

So the issue is related to embedded `iframe`s where the `iframe` navigates to a different origin (e.g. youtube.com).

Compare these logs to the one where an iframe navigates to about:blank:

```html
<html>
    <head></head>
    <body>
        <iframe src=""></iframe>
    </body>
</html>
```

```
// xk6-browser first navigates to about:blank.
onFrameNavigated sid:42A41C3A9B41233D25BCEF6D66D133DA tid:997DCB5956FC7B5D63307C8373556D7C fid:997DCB5956FC7B5D63307C8373556D7C
FrameManager:frameNavigated fid:997DCB5956FC7B5D63307C8373556D7C pfid: docid:A195B4E45ABF20B5A978D18C5D6F2E87 fname: furl:about:blank initial:true
// Now it navigates to a test page with an iframe.
onFrameNavigated sid:42A41C3A9B41233D25BCEF6D66D133DA tid:997DCB5956FC7B5D63307C8373556D7C fid:997DCB5956FC7B5D63307C8373556D7C
FrameManager:frameNavigated fid:997DCB5956FC7B5D63307C8373556D7C pfid: docid:1A0CF3B86D0BF83CE707BFFFA532B166 fname: furl:http://localhost:8080/embed-youtube initial:false
// Chrome sends a signal that a child frame is being attached.
onFrameAttached sid:42A41C3A9B41233D25BCEF6D66D133DA tid:997DCB5956FC7B5D63307C8373556D7C fid:94DFCBB3C80861CA9ECA2B2DDD91D473 pfid:997DCB5956FC7B5D63307C8373556D7C
FrameManager:frameAttached fmid:1 fid:94DFCBB3C80861CA9ECA2B2DDD91D473 pfid:997DCB5956FC7B5D63307C8373556D7C
FrameManager:frameAttached no frame exists fmid:1 fid:94DFCBB3C80861CA9ECA2B2DDD91D473 pfid:997DCB5956FC7B5D63307C8373556D7C
FrameManager:frameAttached new frame fmid:1 fid:94DFCBB3C80861CA9ECA2B2DDD91D473 pfid:997DCB5956FC7B5D63307C8373556D7C
// Navigate to about:blank initially in the iframe (newly attache child frame).
onFrameNavigated sid:42A41C3A9B41233D25BCEF6D66D133DA tid:997DCB5956FC7B5D63307C8373556D7C fid:94DFCBB3C80861CA9ECA2B2DDD91D473
FrameManager:frameNavigated fid:94DFCBB3C80861CA9ECA2B2DDD91D473 pfid:997DCB5956FC7B5D63307C8373556D7C docid:3BF362B038AC26AB7A4861D750329436 fname: furl:about:blank initial:false
```

No detach and attach of frames since the `iframe` is navigating to the same origin as the parent frame.

# Fix

This fix is to not delete the frame with the id in the detach event, but to clean it of its child frames. This will allow the incoming remote frame to attach itself to the same frame that was specified in the detach event.

## Why are you skipping the test?

This issue is non existent when running tests in headless mode, which is how we run tests in CLI. Therefore the test that was written is being skipped.

### CODE REVIEW

File: tests/frame_test.go [hunk 1]
```diff
@@ -72,3 +72,36 @@ func TestFrameDismissDialogBox(t *testing.T) {
...
+
+	var result string
+	err := b.await(func() error {
+		opts := b.toGojaValue(struct {
+			WaitUntil string `js:"waitUntil"`
+		}{
+			WaitUntil: "networkidle",
+		})
+		pageGoto := p.Goto(
+			b.staticURL("embedded_iframe.html"),
```
Comment (imiric) [inline tests/frame_test.go:93]: Did you forget to commit this file? The test fails with a 404 for me, even when enabling headed mode.

File: tests/frame_test.go [hunk 2]
```diff
@@ -72,3 +72,36 @@ func TestFrameDismissDialogBox(t *testing.T) {
 		})
 	}
 }
+
+func TestFrameNoPanicWithEmbeddedIFrame(t *testing.T) {
+	// This test only works when headless mode is false.
+	t.SkipNow()
```
Comment (imiric) [inline tests/frame_test.go:78]: Maybe use `Skip()` and specify the reason there?

And only skip if `XK6_HEADLESS` (or `XK6_BROWSER_TEST_HEADLESS`?) is falsey?

**Review by imiric — COMMENTED** [review]
The fix LGTM, but I think some test issues could be improved.

Thanks for the link on how rendering works in Chrome. I wonder if this fix would also work for Firefox, but we can worry about that later.

I tested the change with the complex script and this does fix the panic. Nice job debugging it and porting the fix from Playwright and Puppeteer :+1:

Do you know why this only happens in headed mode? I know there are subtle differences when running headless, but my assumption was that rendering is pretty much the same.

Since the functionality seems to vary, it might be worth investigating ways of also running headed tests in CI. For example, it seems possible with [XVFB](http://elementalselenium.com/tips/38-headless) and there's a [GH Action](https://github.com/GabrielBB/xvfb-action) for it.

File: tests/frame_test.go (hunk 1 above)
Comment (ankur22) [reply tests/frame_test.go:93]: Thanks for reminding me. Added in 89221d54dfd64d84a879b368eb1d344fa83e244c

File: tests/frame_test.go (hunk 2 above)
Comment (ankur22) [reply tests/frame_test.go]: Good idea. I've added that in.

Resolved in: 2c88222b65722576ac3021eef97a6cb85703e860 and 9044d9a67609e56306994f351f7d22131f1e73b2

File: tests/frame_test.go [hunk 3]
```diff
@@ -72,3 +74,46 @@ func TestFrameDismissDialogBox(t *testing.T) {
 		})
 	}
 }
+
+func TestFrameNoPanicWithEmbeddedIFrame(t *testing.T) {
+	if strValue, ok := os.LookupEnv("XK6_HEADLESS"); ok {
```
Comment (imiric) [inline tests/frame_test.go:79]: Just FYI that there's also a test-specific env var for this: [`XK6_BROWSER_TEST_HEADLESS`](https://github.com/grafana/xk6-browser/blob/3cee653dff64cbd71c86c8fe16ebd9828fe3b58b/tests/test_browser.go#L359).

I forget why @inancgumus wanted to use it instead of `XK6_HEADLESS`, but you can discuss it with him. I think this is fine as well.

File: tests/frame_test.go [hunk 4]
```diff
@@ -72,3 +74,46 @@ func TestFrameDismissDialogBox(t *testing.T) {
 		})
 	}
 }
+
+func TestFrameNoPanicWithEmbeddedIFrame(t *testing.T) {
```
Comment (imiric) [inline tests/frame_test.go:78]: This test races for me on Linux:

<details>
  <summary>Race</summary>

```
$ XK6_HEADLESS= go test -v -race -failfast -count=1 -run 'TestFrameNoPanicWithEmbeddedIFrame' ./tests
=== RUN   TestFrameNoPanicWithEmbeddedIFrame
=== PAUSE TestFrameNoPanicWithEmbeddedIFrame
=== CONT  TestFrameNoPanicWithEmbeddedIFrame
time="2022-12-20T17:21:06+01:00" level=warning msg="url:https://www.youtube.com/embed/gwO7k5RTE54?wmode=opaque&enablejsapi=1 method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:06+01:00" level=warning msg="url:https://www.youtube.com/s/player/34f9b71c/www-player.css method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:06+01:00" level=warning msg="url:https://www.youtube.com/s/player/34f9b71c/fetch-polyfill.vflset/fetch-polyfill.js method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:06+01:00" level=warning msg="url:https://www.youtube.com/s/player/34f9b71c/www-embed-player.vflset/www-embed-player.js method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:06+01:00" level=warning msg="url:https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxK.woff2 method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:06+01:00" level=warning msg="url:https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc4.woff2 method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:06+01:00" level=warning msg="url:https://www.youtube.com/s/player/34f9b71c/player_ias.vflset/en_US/base.js method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:06+01:00" level=error msg="Failed to load resource: net::ERR_SSL_KEY_USAGE_INCOMPATIBLE" browser_source=network line_number=0 source=browser stacktrace="<nil>" url="https://googleads.g.doubleclick.net/pagead/id"
time="2022-12-20T17:21:06+01:00" level=error msg="Failed to load resource: net::ERR_SSL_KEY_USAGE_INCOMPATIBLE" browser_source=network line_number=0 source=browser stacktrace="<nil>" url="https://static.doubleclick.net/instream/ad_status.js"
time="2022-12-20T17:21:06+01:00" level=warning msg="url:https://www.google.com/js/th/YkfklCtf3s5-_1quWHAnTHHVaBZ-i7ToAeXFpu3i2Ro.js method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:06+01:00" level=warning msg="url:https://www.youtube.com/s/player/34f9b71c/player_ias.vflset/en_US/embed.js method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:06+01:00" level=warning msg="url:https://www.youtube.com/s/player/34f9b71c/player_ias.vflset/en_US/remote.js method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:07+01:00" level=warning msg="url:https://yt3.ggpht.com/9mD5UVq9v0F0JsJYQN-zMB8AfV2Wi4SOdF7B2AAxlfekZWgitfj9ewjXhvWmGYJe3RIff0gXWw=s68-c-k-c0x00ffffff-no-rj method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:07+01:00" level=warning msg="url:https://i.ytimg.com/vi_webp/gwO7k5RTE54/default.webp method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:07+01:00" level=warning msg="url:https://jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/Create method:POST err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:07+01:00" level=warning msg="url:https://www.youtube.com/generate_204?_Z3IgA method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:07+01:00" level=warning msg="url:https://jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/GenerateIT method:POST err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:07+01:00" level=warning msg="url:https://www.gstatic.com/cv/js/sender/v1/cast_sender.js method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
time="2022-12-20T17:21:07+01:00" level=warning msg="url:https://www.gstatic.com/eureka/clank/107/cast_sender.js method:GET err:fetching response body: No resource with given identifier found (-32000)" category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=152
==================
WARNING: DATA RACE
Write at 0x00c00050e570 by goroutine 50:
  runtime.mapassign_faststr()
      /home/ivan/.local/share/go/src/runtime/map_faststr.go:203 +0x0
  github.com/grafana/xk6-browser/common.(*FrameManager).requestStarted()
      /home/ivan/Projects/grafana/xk6-browser/common/frame_manager.go:522 +0x2e9
  github.com/grafana/xk6-browser/common.(*NetworkManager).onRequest()
      /home/ivan/Projects/grafana/xk6-browser/common/network_manager.go:441 +0xa1d
  github.com/grafana/xk6-browser/common.(*NetworkManager).handleEvents()
      /home/ivan/Projects/grafana/xk6-browser/common/network_manager.go:334 +0x2e9
  github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents.func1()
      /home/ivan/Projects/grafana/xk6-browser/common/network_manager.go:313 +0x3e

Previous write at 0x00c00050e570 by goroutine 171:
  runtime.mapdelete_faststr()
      /home/ivan/.local/share/go/src/runtime/map_faststr.go:301 +0x0
  github.com/grafana/xk6-browser/common.(*FrameManager).requestFinished()
      /home/ivan/Projects/grafana/xk6-browser/common/frame_manager.go:490 +0x1e9
  github.com/grafana/xk6-browser/common.(*NetworkManager).onLoadingFinished()
      /home/ivan/Projects/grafana/xk6-browser/common/network_manager.go:389 +0x664
  github.com/grafana/xk6-browser/common.(*NetworkManager).handleEvents()
      /home/ivan/Projects/grafana/xk6-browser/common/network_manager.go:332 +0x1ce
  github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents.func1()
      /home/ivan/Projects/grafana/xk6-browser/common/network_manager.go:313 +0x3e

Goroutine 50 (running) created at:
  github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents()
      /home/ivan/Projects/grafana/xk6-browser/common/network_manager.go:312 +0x34e
  github.com/grafana/xk6-browser/common.NewNetworkManager()
      /home/ivan/Projects/grafana/xk6-browser/common/network_manager.go:87 +0x5e4
  github.com/grafana/xk6-browser/common.NewFrameSession()
      /home/ivan/Projects/grafana/xk6-browser/common/frame_session.go:100 +0x73a
  github.com/grafana/xk6-browser/common.NewPage()
      /home/ivan/Projects/grafana/xk6-browser/common/page.go:119 +0xc18
  github.com/grafana/xk6-browser/common.(*Browser).onAttachedToTarget()
      /home/ivan/Projects/grafana/xk6-browser/common/browser.go:274 +0xadb
  github.com/grafana/xk6-browser/common.(*Browser).initEvents.func1()
      /home/ivan/Projects/grafana/xk6-browser/common/browser.go:175 +0x424

Goroutine 171 (running) created at:
  github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents()
      /home/ivan/Projects/grafana/xk6-browser/common/network_manager.go:312 +0x34e
  github.com/grafana/xk6-browser/common.NewNetworkManager()
      /home/ivan/Projects/grafana/xk6-browser/common/network_manager.go:87 +0x5e4
  github.com/grafana/xk6-browser/common.NewFrameSession()
      /home/ivan/Projects/grafana/xk6-browser/common/frame_session.go:100 +0x73a
  github.com/grafana/xk6-browser/common.(*FrameSession).attachIFrameToTarget()
      /home/ivan/Projects/grafana/xk6-browser/common/frame_session.go:847 +0x266
  github.com/grafana/xk6-browser/common.(*FrameSession).onAttachedToTarget()
      /home/ivan/Projects/grafana/xk6-browser/common/frame_session.go:780 +0x476
  github.com/grafana/xk6-browser/common.(*FrameSession).initEvents.func1()
      /home/ivan/Projects/grafana/xk6-browser/common/frame_session.go:259 +0x608
==================
time="2022-12-20T17:21:07+01:00" level=error msg="Failed to load resource: the server responded with a status of 404 (Not Found)" browser_source=network line_number=0 source=browser stacktrace="<nil>" url="http://127.0.0.1:39275/favicon.ico"
    testing.go:1319: race detected during execution of test
--- FAIL: TestFrameNoPanicWithEmbeddedIFrame (1.61s)
FAIL
FAIL    github.com/grafana/xk6-browser/tests    1.652s
```
</details>

It doesn't seem related to the changes here, and it also happens on `main`, with _many_ more data races, so at least it's an improvement? :smile:

File: tests/static/embedded_iframe.html [hunk 5]
```diff
@@ -0,0 +1,7 @@
+<html>
+    <head></head>
+    <body>
+        <div id='doneDiv'></div>
+        <iframe src='https://www.youtube.com/embed/gwO7k5RTE54?wmode=opaque&amp;enablejsapi=1' onload='document.getElementById("doneDiv").innerText = "Done!"'></iframe>
```
Comment (imiric) [inline tests/static/embedded_iframe.html:5]: Maybe let's not use `youtube.com` here, but something we control, like test.k6.io?

**Review by imiric — APPROVED** [review]
LGTM :+1:

Just left some minor things. Feel free to ignore or address later.

File: tests/frame_test.go (hunk 3 above)
Comment (ankur22) [reply tests/frame_test.go:79]: I saw that too, i'll stick with `XK6_HEADLESS` for now 👍

File: tests/frame_test.go (hunk 4 above)
Comment (ankur22) [reply tests/frame_test.go:78]: 😩 we run into new data race issues a lot still. I've created issue [#680](https://github.com/grafana/xk6-browser/issues/680) to track it.

File: tests/static/embedded_iframe.html (hunk 5 above)
Comment (ankur22) [reply tests/static/embedded_iframe.html:5]: I tried that earlier, but it didn't fail :/ I'm not sure what youtube.com does that forces the locel -> remote frame transition.

File: tests/frame_test.go (hunk 3 above)
Comment (inancgumus) [reply tests/frame_test.go:79]: IIRC, we decided to prefix environment variables with `XK6_BROWSER` to be explicit and prevent clashes with other extensions.

**Comment by inancgumus** [comment]
@ankur22 Nice explanations and thanks for the fix 👍
