### PR TITLE
Fix context.clearCookies

### LINKED ISSUE #442: Cookies: Clearing cookies fails
Tested against: dbede120c63df43995813a847a25b0e66e289592

When `ClearCookies` is called on `BrowserContext` it panics and fails to clear the cookies ending with the following error:

```
unable to clear cookies permissions: invalid context
```

The javascript test used was:

```javascript
import { sleep } from 'k6';
import launcher from 'k6/x/browser';

export default function () {
  const browser = launcher.launch('chromium', {
      headless: false,
  });
  const context = browser.newContext();
  const page = context.newPage();
  const res = page.goto('https://test.k6.io/browser.php');
  context.clearCookies();

  sleep(10);
  browser.close();
}
```

The expected result is that it clears the cookies for all pages that were opened from the relevant context.

The Playwright test code is:

```javascript
// @ts-check
const { test, chromium } = require('@playwright/test');

test.describe('Editing', () => {
  test('Type login creds', async () => {
    const browser = await chromium.launch({ headless: false, slowMo: 500 });
    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    await page.goto('https://test.k6.io/browser.php');
    await ctx.clearCookies();

    await new Promise(resolve => setTimeout(resolve, 10000));

    await browser.close();
  });
});
```

### PR DESCRIPTION
**Pull request by inancgumus**
## What?

Fixes the _"unable to clear cookies permissions: invalid context"_ error. This error occurs when `browserContext.clearCookies` is called. See #442 for details.

## Why?

The `clearCookies` method wasn't using the actual CDP connection.

## Checklist

- [x] I have performed a self-review of my code
- [ ] I have added tests for my changes
- [ ] I have commented on my code, particularly in hard-to-understand areas

## Related PR(s)/Issue(s)

Closes #442

### CODE REVIEW

**Review by ankur22 — DISMISSED** [review]
Love these seemingly straight forward fixes 🎉 LGTM

File: common/browser_context.go [hunk 1]
```diff
@@ -502,7 +502,7 @@ func (b *BrowserContext) ClearCookies() error {
 	clearCookies := storage.
 		ClearCookies().
 		WithBrowserContextID(b.id)
-	if err := clearCookies.Do(b.ctx); err != nil {
+	if err := clearCookies.Do(cdp.WithExecutor(b.ctx, b.browser.conn)); err != nil {
```
Comment (ka3de) [inline common/browser_context.go:505]: Should we add a test for this functionality? Maybe it also makes sense to use it in the cookies example if you think it fits.

Comment (inancgumus) [reply common/browser_context.go:505]: Good points 👍 See: https://github.com/grafana/xk6-browser/pull/1040/commits/1297e3b0b9d36accb0f47971607a8835bbdd782a and https://github.com/grafana/xk6-browser/pull/1040/commits/019a02db8d24221c750610297f252179ed797bf9.

**Review by ankur22 — APPROVED** [review]
LGTM

**Review by ka3de — APPROVED** [review]
Polishing the :cookie: functionality! LGTM.

**Comment by inancgumus** [comment]
> Polishing the 🍪 functionality! LGTM.

Cookies 🍪 🍪!!
