### PR TITLE
Map [Page|Frame].WaitForFunction promises and fix tests

### LINKED ISSUE #708: Map [Page|Frame].WaitForFunction promises and fix tests
This issue is about mapping `Page.WaitForFunction` and `Frame.WaitForFunction` methods in the mapping layer.

See issue #683 for more details.

### PR DESCRIPTION
**Pull request by inancgumus**
The tests still need some refactoring, but it's out of focus for this PR. I tried to make them pass without changing things much.

Ideally, these tests should be written by the JavaScript side (as we'll do in #675). They are entirely concerned about the JS side of things, and these Go tests become futile, complicated, and hard to understand and maintain.

Closes #708. Updates #683.

### CODE REVIEW

File: tests/page_test.go [hunk 1]
```diff
@@ -440,12 +440,13 @@ func TestPageSetExtraHTTPHeaders(t *testing.T) {
...
+	// waitForFunction call itself and the tests that use it are
+	// testing the polling functionality—not the response from
+	// waitForFunction.
 	script := `
-        page.waitForFunction(%s, %s, %s).then(ok => {
-            log('ok: '+ok);
-        }, err => {
-            log('err: '+err);
-        });`
+		let resp = page.waitForFunction(%s, %s, %s)
```
Comment (ankur22) [inline tests/page_test.go:448]: Do we not need `await` here? Otherwise it could print `ok: `, no?

**Review by ankur22 — COMMENTED** [review]
LGTM, just wondering about whether we need to await on the script in the tests?

**Review by ankur22 — APPROVED** [review]

File: tests/page_test.go (hunk 1 above)
Comment (inancgumus) [reply tests/page_test.go:448]: ❤️
