### PR TITLE
Map [Page|Frame].Goto promises and fix tests

### LINKED ISSUE #705: Map [Page|Frame].Goto promises and fix tests
This issue is about mapping `Page.Goto` and `Frame.Goto` methods in the mapping layer.

See issue #683 for more details.

### PR DESCRIPTION
**Pull request by inancgumus**
This PR removes the promise handling from the `Goto` methods and moves the handling to the mapping layer. Sorry, the PR is pretty big. It wasn't possible to split it into more commits without breaking tests. I hope you'll be able to review it. One tip is to review each file from the `Files changed` tab with the file navigation on. Depends on your preference. Feel free to let me know if you have any questions.

PS: I kept the fixup commits for your convenience. I'll squash them all when you finish reviewing. That's why it's not in the "ready for review" yet; still a draft.

Closes #705. Updates #683.

### CODE REVIEW

File: tests/browser_context_options_test.go [hunk 1]
```diff
@@ -77,14 +76,16 @@ func TestBrowserContextOptionsExtraHTTPHeaders(t *testing.T) {
...
 	err := tb.awaitWithTimeout(time.Second*5, func() error {
-		tb.promise(p.Goto(tb.URL("/get"), nil)).then(func(resp api.Response) {
-			require.NotNil(t, resp)
-			var body struct{ Headers map[string][]string }
-			require.NoError(t, json.Unmarshal(resp.Body().Bytes(), &body))
-			h := body.Headers["Some-Header"]
-			require.NotEmpty(t, h)
-			assert.Equal(t, "Some-Value", h[0])
-		})
+		resp, err := p.Goto(tb.URL("/get"), nil)
```
Comment (inancgumus) [inline tests/browser_context_options_test.go:79]: Forgot this, little one: No need to use `awaitWithTimeout` here.

**Comment by inancgumus** [comment]
@ankur22 Could you review this, so I can work on the next sub-feature w/o conflicts etc 🙇

**Review by ankur22 — APPROVED** [review]
LGTM
