### PR TITLE
Fix injected script's Shadow DOM parsing

### LINKED ISSUE #1046: WaitForSelector causes a deadlock
### Brief summary

The test run ID 1965253 fails on production with the following message.

```
SIGQUIT: quit
PC=0x472e21 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex()
	runtime/sys_linux_amd64.s:557 +0x21 fp=0x7ffea4b38150 sp=0x7ffea4b38148 pc=0x472e21
runtime.futexsleep(0x7ffea4b381c8?, 0x442316?, 0x7ffea4b381c8?)
	runtime/os_linux.go:69 +0x30 fp=0x7ffea4b381a0 sp=0x7ffea4b38150 pc=0x437630
runtime.notesleep(0x276a2c8)
	runtime/lock_futex.go:160 +0x87 fp=0x7ffea4b381d8 sp=0x7ffea4b381a0 pc=0x40eb67
runtime.mPark(...)
	runtime/proc.go:1632
runtime.stoplockedm()
	runtime/proc.go:2780 +0x73 fp=0x7ffea4b38230 sp=0x7ffea4b381d8 pc=0x4424f3
runtime.schedule()
	runtime/proc.go:3561 +0x3a fp=0x7ffea4b38268 sp=0x7ffea4b38230 pc=0x44433a
runtime.park_m(0xc0017acd00?)
	runtime/proc.go:3745 +0x11f fp=0x7ffea4b382b0 sp=0x7ffea4b38268 pc=0x4448bf
runtime.mcall()
	runtime/asm_amd64.s:458 +0x4e fp=0x7ffea4b382c8 sp=0x7ffea4b382b0 pc=0x46f16e

goroutine 1 [chan receive, 14 minutes]:
runtime.gopark(0xc0020cc668?, 0x4103a5?, 0x80?, 0xb5?, 0x40?)
	runtime/proc.go:398 +0xce fp=0xc0030f8600 sp=0xc0030f85e0 pc=0x43df8e
runtime.chanrecv(0xc00059d9e0, 0xc0020cc7a0, 0x1)
	runtime/chan.go:583 +0x3cd fp=0xc0030f8678 sp=0xc0030f8600 pc=0x4099ad
runtime.chanrecv1(0x19d7fe0?, 0xc00112e3c0?)
	runtime/chan.go:442 +0x12 fp=0xc0030f86a0 sp=0xc0030f8678 pc=0x4095b2
go.k6.io/k6/execution.(*Scheduler).Run(0xc0000e55e0, {0x19d8018, 0xc000100cd0}, {0x19d7fe0, 0xc000680ba0}, 0xc0012e7380)
	go.k6.io/k6/execution/scheduler.go:472 +0xc6e fp=0xc0030f8e78 sp=0xc0030f86a0 pc=0x83214e
go.k6.io/k6/cmd.(*cmdRun).run(0xc000066340, 0xc0001c1900, {0xc0002f7340?, 0x1, 0x2c})
	go.k6.io/k6/cmd/run.go:352 +0x1531 fp=0xc0030f9c30 sp=0xc0030f8e78 pc=0x138c951
go.k6.io/k6/cmd.(*cmdRun).run-fm(0xc00003fd00?, {0xc0002f7340?, 0x4?, 0x16e67ca?})
	<autogenerated>:1 +0x34 fp=0xc0030f9c68 sp=0xc0030f9c30 pc=0x13970b4
github.com/spf13/cobra.(*Command).execute(0xc0001c1900, {0xc0002f7080, 0x2c, 0x2c})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x694 fp=0xc0030f9d50 sp=0xc0030f9c68 pc=0x5b8734
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002f4f0
... omitting 103716 bytes ...
+0xb6

goroutine 1046 [select, 6 minutes]:
runtime.gopark(0xc0007947a8?, 0x2?, 0xff?, 0xff?, 0xc00079479c?)
	runtime/proc.go:398 +0xce fp=0xc000794640 sp=0xc000794620 pc=0x43df8e
runtime.selectgo(0xc0007947a8, 0xc000794798, 0xc0007947b8?, 0x0, 0xc0007947d0?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc000794760 sp=0xc000794640 pc=0x44e405
github.com/grafana/xk6-browser/common.contextWithDoneChan.func1()
	github.com/grafana/xk6-browser@v1.0.2/common/context.go:61 +0x7c fp=0xc0007947e0 sp=0xc000794760 pc=0x115af5c
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0007947e8 sp=0xc0007947e0 pc=0x470fe1
created by github.com/grafana/xk6-browser/common.contextWithDoneChan in goroutine 77
	github.com/grafana/xk6-browser@v1.0.2/common/context.go:59 +0xb6

goroutine 726 [select, 14 minutes]:
runtime.gopark(0xc000892788?, 0x2?, 0x50?, 0x26?, 0xc00089277c?)
	runtime/proc.go:398 +0xce fp=0xc000892628 sp=0xc000892608 pc=0x43df8e
runtime.selectgo(0xc000892788, 0xc000892778, 0xc0006c3080?, 0x0, 0xc0020635e0?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc000892748 sp=0xc000892628 pc=0x44e405
github.com/grafana/xk6-browser/common.(*BaseEventEmitter).syncAll(0xc0023d8640, {0x19d8018, 0xc000f2f310})
	github.com/grafana/xk6-browser@v1.0.2/common/event_emitter.go:130 +0xa5 fp=0xc0008927b8 sp=0xc000892748 pc=0x116fb25
github.com/grafana/xk6-browser/common.NewBaseEventEmitter.func1()
	github.com/grafana/xk6-browser@v1.0.2/common/event_emitter.go:120 +0x28 fp=0xc0008927e0 sp=0xc0008927b8 pc=0x116fa48
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0008927e8 sp=0xc0008927e0 pc=0x470fe1
created by github.com/grafana/xk6-browser/common.NewBaseEventEmitter in goroutine 98
	github.com/grafana/xk6-browser@v1.0.2/common/event_emitter.go:120 +0x199
```

---

Possible related issues: #200 and #172.

### xk6-browser version

v1.0.2

### OS

Remote

### Chrome version

Remote

### Docker version and image (if applicable)

_No response_

### Steps to reproduce the problem

Run the test script locally.

### Expected behaviour

No deadlock.

### Actual behaviour

Deadlocks.

### PR DESCRIPTION
**Pull request by ka3de**
## What?

Fixes the` _exploreShadowDOM` function defined in the `js/injected_script.js` to check for root's children before recursively exploring them.

## Why?

This bug was producing sporadic deadlocks in `frame.waitForSelector` method.

## Checklist

- [X] I have performed a self-review of my code
- [ ] I have added tests for my changes
- [ ] I have commented on my code, particularly in hard-to-understand areas

## Related PR(s)/Issue(s)
Closes #1046 .

### CODE REVIEW

**Review by ankur22 — DISMISSED** [review]
LGTM 🚀

File: common/js/injected_script.js [hunk 1]
```diff
@@ -248,6 +248,8 @@ class InjectedScript {
       );
       result = result.concat(shadowRootResults);
     }
+
+    if (root.children === undefined) return result;
```
Comment (inancgumus) [inline common/js/injected_script.js:252]: Should we use [`hasChildNodes`](https://developer.mozilla.org/en-US/docs/Web/API/Node/hasChildNodes)?

```suggestion
    if (!root.hasChildNodes()) return result;
```

**Review by inancgumus — COMMENTED** [review]
Thanks for working on this and coming up with a fix 👍 

As far as I can see, this test doesn't check the shadow-DOM behavior (as we discussed earlier). Because removing the condition you added in `injected_script` doesn't make a difference to the test—the test always passes.

The test adds 3 seconds to the total run (about 10% of our whole test run). I've tried making the `timeout: 10` in the test and `setTimeout(..., 100)`. Then, I ran the test 100 times successfully.  Each took ~1 sec.

Other than that, this test might still need improvement because it can be flaky. Is it better to make the DIV visible while the second test case waits? So that we won't need to use a timeout.

File: common/js/injected_script.js (hunk 1 above)
Comment (ka3de) [reply common/js/injected_script.js]: We can do that. See [a03cc81](https://github.com/grafana/xk6-browser/pull/1049/commits/a03cc813f08b3de530192c9e94a9bf8c2166382d).

**Comment by ka3de** [comment]
> do we need this test?

We do not have any test for `page.waitForSelector`, so I would say we should keep them.

> The test adds 3 seconds to the total run (about ~15% of our whole test run) 😢 I've tried making the timeout: 10 in the test and setTimeout(..., 100). Then, I ran the test 100 times successfully. Each took ~1 sec. Should we do it like so?

The tests run in parallel, right? So it's not adding 3 seconds to the total run. I've run the tests twice with (16.083s and 16.622s for `tests` pkg) and without this test (16.025s and 16.366s) and did not see much difference. Still, we can try to fine tune it to reduce the time, but it gets flakier as we try to squeeze the times.

> Is it better to make the DIV visible using page.evaluate or something similar (by directly changing the div visibility) while the second test case waits?

I usually try to use the minimum number of methods of our own implementation in tests away from the actual method being tested, even if it's an integration test.

I've reduced the times in [0ae3429](https://github.com/grafana/xk6-browser/pull/1049/commits/0ae3429d9210c30f24954a81bd313c661797cbc7) and seems to be running fine consistently.

**Review by inancgumus — APPROVED** [review]
> The tests run in parallel, right?

It was my mistake to run the test individually 🤦‍♂️ It's negligible when run with others 👍

> I usually try to use the minimum number of methods of our own implementation in tests away from the actual method being tested, even if it's an integration test.

I see your point, and I agree: The tests should reveal their logic easily and test the minimum things they target so that one failure from other parts of the system can't leak into the current test. Still, that's a fair trade-off to use other methods in tests, even if it may make the tests less self-contained. It's better than having _possibly_ flaky tests.

> I've reduced the times in [0ae3429](https://github.com/grafana/xk6-browser/pull/1049/commits/0ae3429d9210c30f24954a81bd313c661797cbc7) and seems to be running fine consistently.

Thanks!
