### PR TITLE
fixes panic for the selectOption

### LINKED ISSUE #1415: Unable to selectOption using object
### Brief summary

Unable to selectOption using object as described here: https://grafana.com/docs/k6/latest/javascript-api/k6-browser/locator/selectoption/
> If the select has the multiple attribute, all matching options are selected, otherwise only the first option matching one of the passed options is selected. Object can be made up of keys with value, label or index.

Supported by Playwright: https://playwright.dev/docs/input#select-options

Example: `options.selectOption({label:'Five'})`

### xk6-browser version

128.0.6613.115

### OS

Windows 11 Enterprise, 10.0.22631 Build 22631

### Chrome version

128.0.6613.115

### Docker version and image (if applicable)

_No response_

### Steps to reproduce the problem

```
import { browser } from 'k6/browser';

export const options = {
  scenarios: {
    browser: {
      executor: 'shared-iterations',
      options: {
        browser: {
          type: 'chromium',
        },
      },
    },
  },
};

export default async function () {
  const page = await browser.newPage();
  await page.goto('https://test.k6.io/browser.php');
  const options = page.locator('#numbers-options');
  await options.selectOption({label:'Five'});
}
```

### Expected behaviour

Selecting "Five" from the numbers-options selection box

### Actual behaviour

```
panic: reflect: call of reflect.Value.Index on map Value
running (00m02.9s), 1/1 VUs, 0 complete and 0 interrupted iterations
goroutine 259 [running]:-------------------------] 1 VUs  00m02.9s/10m0s  0/1 shared iters
reflect.Value.Index({0x239ee60?, 0xc000567230?, 0xc000048460?}, 0xeea9fd?)
        reflect/value.go:1447 +0x154
github.com/grafana/xk6-browser/common.(*ElementHandle).selectOption.func1({0x29dafd8, 0xc000464ff0})
        github.com/grafana/xk6-browser@v1.7.0/common/element_handle.go:495 +0x828
github.com/grafana/xk6-browser/common.(*ElementHandle).selectOption(0xc000518640, {0x29c67f8, 0xc00046e2a0}, {0x29dafd8?, 0xc000464ff0?})
        github.com/grafana/xk6-browser@v1.7.0/common/element_handle.go:551 +0x63
github.com/grafana/xk6-browser/common.(*Frame).selectOption.func1({0x29c67f8?, 0xc00046e2a0?}, 0xc00046e2a0?)
        github.com/grafana/xk6-browser@v1.7.0/common/frame.go:1502 +0x34
github.com/grafana/xk6-browser/common.(*ElementHandle).newAction.func1({0x29c67f8, 0xc00046e2a0})
        github.com/grafana/xk6-browser@v1.7.0/common/element_handle.go:1545 +0x1b3
github.com/grafana/xk6-browser/common.(*ElementHandle).newAction.func2({0x29c67f8?, 0xc00046e2a0?}, 0xc0004e6720, 0xc0004e6780)
        github.com/grafana/xk6-browser@v1.7.0/common/element_handle.go:1560 +0x3b
github.com/grafana/xk6-browser/common.(*Frame).selectOption.(*Frame).newAction.func2({0x29c67f8, 0xc00046e2a0}, 0xc0004e6720, 0xc0004e6780)
        github.com/grafana/xk6-browser@v1.7.0/common/frame.go:2117 +0x178
created by github.com/grafana/xk6-browser/common.call in goroutine 258
        github.com/grafana/xk6-browser@v1.7.0/common/helpers.go:103 +0x14c
```

### PR DESCRIPTION
**Pull request by olegbespalov**
## What?

This PR aims to fix the panic from #1415, by trying to stick with the types that we explicitly mention in our documentation https://grafana.com/docs/k6/latest/javascript-api/k6-browser/locator/selectoption/

## Why?

We shouldn't panic

## Checklist

- [ ] I have performed a self-review of my code
- [x] I have added tests for my changes
- [ ] I have commented on my code, particularly in hard-to-understand areas

## Related PR(s)/Issue(s)

Closes #1415 

Fixes #https://github.com/grafana/k6/issues/4071

### CODE REVIEW

File: common/tests/cmd_test.go [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+
+	"go.k6.io/k6/cmd"
+	k6tests "go.k6.io/k6/cmd/tests"
+)
+
+func TestCmd(t *testing.T) {
+	t.Skip("data race")
```
Comment (olegbespalov) [inline common/tests/cmd_test.go:14]: This test for now is skipped because it causes data race

```
==================
WARNING: DATA RACE
Write at 0x00c0003076d0 by goroutine 24:
  runtime.closechan()
      /home/olegbespalov/.go/src/runtime/chan.go:397 +0x0
  go.k6.io/k6/cmd.(*cmdRun).run.func11()
      /home/olegbespalov/go/pkg/mod/go.k6.io/k6@v0.54.0/cmd/run.go:274 +0xc5
  runtime.deferreturn()
      /home/olegbespalov/.go/src/runtime/panic.go:605 +0x5d
  go.k6.io/k6/cmd.(*cmdRun).run-fm()
      <autogenerated>:1 +0x64
  github.com/spf13/cobra.(*Command).execute()
      /home/olegbespalov/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0xbbd
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/olegbespalov/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x617
  github.com/spf13/cobra.(*Command).Execute()
      /home/olegbespalov/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902 +0x24c
  go.k6.io/k6/cmd.(*rootCommand).execute()
      /home/olegbespalov/go/pkg/mod/go.k6.io/k6@v0.54.0/cmd/root.go:108 +0x228
  go.k6.io/k6/cmd.ExecuteWithGlobalState()
      /home/olegbespalov/go/pkg/mod/go.k6.io/k6@v0.54.0/cmd/root.go:137 +0x2b
  github.com/grafana/xk6-browser/common/tests.TestCmd()
      /home/olegbespalov/projects/grafana/k6/xk6-browser/common/tests/cmd_test.go:53 +0x29e
  testing.tRunner()
      /home/olegbespalov/.go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /home/olegbespalov/.go/src/testing/testing.go:1743 +0x44

Previous read at 0x00c0003076d0 by goroutine 108:
  runtime.chansend()
      /home/olegbespalov/.go/src/runtime/chan.go:171 +0x0
  go.k6.io/k6/metrics.PushIfNotDone()
      /home/olegbespalov/go/pkg/mod/go.k6.io/k6@v0.54.0/metrics/sample.go:135 +0x77d
  github.com/grafana/xk6-browser/common.(*FrameSession).parseAndEmitWebVitalMetric()
      /home/olegbespalov/projects/grafana/k6/xk6-browser/common/frame_session.go:365 +0x543
  github.com/grafana/xk6-browser/common.(*FrameSession).onEventBindingCalled()
      /home/olegbespalov/projects/grafana/k6/xk6-browser/common/frame_session.go:321 +0x26b
  github.com/grafana/xk6-browser/common.(*FrameSession).initEvents.func1()
      /home/olegbespalov/projects/grafana/k6/xk6-browser/common/frame_session.go:309 +0x535

Goroutine 24 (running) created at:
  testing.(*T).Run()
      /home/olegbespalov/.go/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      /home/olegbespalov/.go/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      /home/olegbespalov/.go/src/testing/testing.go:1690 +0x226
  testing.runTests()
      /home/olegbespalov/.go/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      /home/olegbespalov/.go/src/testing/testing.go:2034 +0xf17
  main.main()
      _testmain.go:45 +0x164

Goroutine 108 (finished) created at:
  github.com/grafana/xk6-browser/common.(*FrameSession).initEvents()
      /home/olegbespalov/projects/grafana/k6/xk6-browser/common/frame_session.go:239 +0x385
  github.com/grafana/xk6-browser/common.NewFrameSession()
      /home/olegbespalov/projects/grafana/k6/xk6-browser/common/frame_session.go:148 +0xa07
  github.com/grafana/xk6-browser/common.NewPage()
      /home/olegbespalov/projects/grafana/k6/xk6-browser/common/page.go:307 +0xc97
  github.com/grafana/xk6-browser/common.(*Browser).onAttachedToTarget()
      /home/olegbespalov/projects/grafana/k6/xk6-browser/common/browser.go:317 +0x5c8
  github.com/grafana/xk6-browser/common.(*Browser).initEvents.func1()
      /home/olegbespalov/projects/grafana/k6/xk6-browser/common/browser.go:234 +0x464
==================
--- FAIL: TestCmd (1.02s)
    testing.go:1399: race detected during execution of test
FAIL
FAIL    github.com/grafana/xk6-browser/common/tests     1.137s
```

File: common/tests/cmd_test.go [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+				},
+			},
+		},
+		};
+
+		export default async function () {
+		const page = await browser.newPage();
+		await page.goto('https://test.k6.io/browser.php');
+		const options = page.locator('#numbers-options');
+		await options.selectOption({label:'Five'});
```
Comment (olegbespalov) [inline common/tests/cmd_test.go:43]: @ankur22 @inancgumus any tips on how to better test this keeping in mind the current test structure?

I took a look into the `tests` package and not sure what could be the best way to emulate input like that (and below).

Comment (olegbespalov) [reply common/tests/cmd_test.go:43]: Basically, I've created this to be like the [ones that k6-core uses](https://github.com/grafana/k6/blob/master/cmd/tests/eventloop_test.go#L122-L130).

My predominant concern is why it should start from JS is because partially the `panic` was caused because of some "magic" sobek type transitioning, and I'd like to keep it as part of the test, to ensure that it works

File: common/tests/cmd_test.go (hunk 1 above)
Comment (olegbespalov) [reply common/tests/cmd_test.go:14]: I'm wondering if that's the issue itself, keeping in mind that data race is coming from the places which haven't part of the diff

Comment (ankur22) [reply common/tests/cmd_test.go:14]: This is strange. So it looks like we're trying to write a metric, but at the same time the `state.Sample` is being closed. I would have expected the context to have been done before the `sample` was closed so that it is not written to the channel in `PushIfNotDone`.

Comment (ankur22) [reply common/tests/cmd_test.go:14]: If i comment out [this](https://github.com/grafana/k6/blob/feb4ac9d42527638c1df17a3e6b36216ea8ffb31/metrics/sample.go#L135), the test you wrote works. Is the race condition in k6? Happy to pair on this debugging session as it will help me understand the lifecycle of k6.

File: common/tests/cmd_test.go (hunk 2 above)
Comment (ankur22) [reply common/tests/cmd_test.go:43]: I really like how you wrote the test, it's much more succinct to how we do it.

If we can't sort the race condition out, then take a look at a test that works with `startIteration`, such as [TestPageOnMetric](https://github.com/grafana/xk6-browser/blob/5aa78f53dad26715613ac6e83cdcc57c9c4acba2/tests/page_test.go#L1887).

File: common/tests/cmd_test.go (hunk 1 above)
Comment (olegbespalov) [reply common/tests/cmd_test.go:14]: Yes, it works, but it reports about the data race if you run the tests with the race detection

```
go test -timeout 30s -race -run ^TestCmd$ github.com/grafana/xk6-browser/common/tests
```

Yep, let's pair on that! I've double-checked and it's actually report of data race (same) for other browser scripts input :cry:

File: tests/locator_test.go [hunk 3]
```diff
@@ -665,3 +672,89 @@ func TestLocatorShadowDOM(t *testing.T) {
...
+			let selectedValue = await options.inputValue();
+			if (selectedValue !== 'five') {
+				throw new Error('Expected "five" but got ' + selectedValue);
+			}
+			await options.selectOption({index:5});
+			selectedValue = await options.inputValue();
+			if (selectedValue !== 'five') {
+				throw new Error('Expected "five" but got ' + selectedValue);
+			}
+			await options.selectOption({value:'five'});
```
Comment (olegbespalov) [inline tests/locator_test.go:735]: TODO(olegbespalov): adjust the tests to pick different select options to check that we actually pick the intendant one, but not checking the "five" from the previous working pick

**Review by ankur22 — APPROVED** [review]
LGTM 🚀
